id: I6B042140
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:52:25+00:00'
last_modified: '2022-06-08T11:49:06.921176+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4957
  title: ཚིག་དོན་རིན་པོ་ཆེའི་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    31AE:
      image_group_id: I3CN4959
      title: ''
      total_pages: 440
      order: 1
      base_file: 31AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
