id: P009549
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:37:34.620020
source_metadata:
  id: bdr:W3CN4957
  title: ཚིག་དོན་རིན་པོ་ཆེའི་མཛོད།
  author: ''
  volumes:
    a7fae9dfa9d04fb394f206a41895a53c:
      image_group_id: I3CN4959
      title: ''
      volume_number: 1
      total_pages: 440
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
